export default {
  sectionName: "事件",
  children: [
    {
      helpText: "选中行时触发",
      propertyName: "onRowSelected",
      label: "onRowSelected",
      controlType: "ACTION_SELECTOR",
      isJSConvertible: true,
      isBindProperty: true,
      isTriggerProperty: true,
    },
    {
      helpText: "表格换页时触发",
      propertyName: "onPageChange",
      label: "onPageChange",
      controlType: "ACTION_SELECTOR",
      isJSConvertible: true,
      isBindProperty: true,
      isTriggerProperty: true,
    },
    {
      helpText: "表格页大小改变时触发",
      propertyName: "onPageSizeChange",
      label: "onPageSizeChange",
      controlType: "ACTION_SELECTOR",
      isJSConvertible: true,
      isBindProperty: true,
      isTriggerProperty: true,
    },
    {
      propertyName: "onSearchTextChanged",
      label: "onSearchTextChanged",
      controlType: "ACTION_SELECTOR",
      isJSConvertible: true,
      isBindProperty: true,
      isTriggerProperty: true,
    },
    {
      helpText: "表格列排序时触发",
      propertyName: "onSort",
      label: "onSort",
      controlType: "ACTION_SELECTOR",
      isJSConvertible: true,
      isBindProperty: true,
      isTriggerProperty: true,
    },
  ],
};
